# Generated by Django 4.1.4 on 2022-12-08 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название БПЛА')),
                ('velocity', models.IntegerField(verbose_name='Скорость БПЛА')),
                ('maximum_gforce', models.IntegerField(verbose_name='Максимальная перегрузка БПЛА')),
                ('volume', models.IntegerField(verbose_name='Объем топлива БПЛА')),
                ('on_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('on_change', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя пользователя')),
                ('on_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('on_change', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Пользователь',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название маршрута')),
                ('points', models.TextField()),
                ('on_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('on_change', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('uav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='uav.uav')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='uav.user')),
            ],
        ),
    ]
