# Generated by Django 4.1.4 on 2022-12-09 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название события')),
                ('content', models.TextField()),
                ('place', models.TextField()),
                ('on_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания события')),
                ('on_change', models.DateTimeField(auto_now=True, verbose_name='Время изменения события')),
            ],
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AlterModelOptions(
            name='uav',
            options={'verbose_name': 'БПЛА', 'verbose_name_plural': 'БПЛА'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='route',
            name='user',
        ),
        migrations.AddField(
            model_name='route',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='В использовании'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название маршрута'),
        ),
        migrations.AlterField(
            model_name='uav',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название БПЛА'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя пользователя'),
        ),
        migrations.CreateModel(
            name='StatusUav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'На задании'), (1, 'Ожидает')], verbose_name='Название статуса')),
                ('on_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('on_change', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('uav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='uav.uav')),
            ],
            options={
                'verbose_name': 'Статус БПЛА',
                'verbose_name_plural': 'Статусы БПЛА',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название боевой задачи')),
                ('content', models.TextField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='uav.route')),
                ('uav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uav', to='uav.uav')),
            ],
        ),
    ]
