# Generated by Django 4.1.4 on 2022-12-09 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0002_event_alter_route_options_alter_uav_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusuav',
            name='uav',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='uav.uav', unique=True),
        ),
    ]
