# Generated by Django 4.1.4 on 2022-12-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0003_alter_statusuav_uav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(verbose_name='Описание события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.TextField(verbose_name='Место регистрации события'),
        ),
        migrations.AlterField(
            model_name='route',
            name='points',
            field=models.TextField(verbose_name='Точки маршрута'),
        ),
    ]
