# Generated by Django 4.1.4 on 2022-12-09 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0004_alter_event_content_alter_event_place_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
