# Generated by Django 4.1.4 on 2022-12-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0005_alter_event_options_alter_problem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='content',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='name',
        ),
    ]
