# Generated by Django 4.1.4 on 2022-12-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0006_remove_problem_content_remove_problem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='name',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Название боевой задачи'),
            preserve_default=False,
        ),
    ]
