# Generated by Django 4.1.4 on 2022-12-11 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0007_problem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uav',
            name='volume',
        ),
    ]
